# Generated by Django 5.1.5 on 2025-01-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_name', models.CharField(max_length=100)),
                ('usr_age', models.IntegerField()),
                ('usr_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
